language: cpp
os: linux
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - cmake
      - libgmp-dev
    update: true

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
